### PR TITLE
feat: compatibility with systemjs 0.18

### PR DESCRIPTION
**Pull request by douglasduteil**
Following https://github.com/systemjs/systemjs/issues/744

### CODE REVIEW

**Comment by douglasduteil** [comment]
Any news about this?
I'm about to make a unofficial fork on npm with @wprater commit and mine 'cause I need it ...

**Comment by douglasduteil** [comment]
Alright it's out !!!
~~https://github.com/douglasduteil/jspm-loader-css/tree/next
https://www.npmjs.com/package/douglasduteil-jspm-loader-css~~

**Update: I unpublished the whole fork !**

**Comment by douglasduteil** [comment]
ping @f15gdsy @wprater @geelen

**Comment by geelen** [comment]
@douglasduteil sorry!!! :cry: 

I haven't had any headspace for JSPM changes since starting my new job & CSS Modules going bananas :banana:, so I've been ignoring my notifications for a while. But I am carving out today to figure out where things are at.

I'd be happy to give you commit/publish access to keep this project going along, since I'm not working with JSPM at my current contract (runs until the end of the year)

**Comment by douglasduteil** [comment]
@geelen Alright I'm looking forward to it :tada: 
Keep me posted about what you're doing with CSS Modules ! I love the idea :heart:

**Pull request merged**
