### PR TITLE
Use correct System variable when bundled.

### PR DESCRIPTION
**Pull request by elliotlings**
When bundling System is renamed to something like $__System. This fix will check for this.

### CODE REVIEW

**Comment by manveru** [comment]
@geelen any chance you could merge this to fix bundling?

**Comment by oligot** [comment]
I tested this PR with https://github.com/css-modules/jspm-demo
And there is still one single call to _System.register_ in the bundle

``` JavaScript
System.register("2", [], function($__export) {
  "use strict";
  var __moduleName = "2";
  return {
    setters: [],
    execute: function() {
      $__export('default', {
        "darkblue": "#001f3f",
        "lol": "_src_main__lol _src_backgrounds__lightBlueBackground _src_a__whiteBorder _src_b__fontSize24pt _src_b__dashed-border"
      });
    }
  };
});
```

@geelen Any idea why it's not using _$__System_ ?

**Comment by oligot** [comment]
I just found that the problem will be solved when PR #44 is merged.

**Comment by juliogarciag** [comment]
It's merged. What is missing is a release.

**Pull request merged**
